/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.ids.justmeet.webapp;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
